name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Build Dependencies
        run: |
          choco install make
          choco install miktex
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv

      - name: Build
        # cannot run release task on Windows
        run: make all

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: ./*.pdf
